# 🔢 NumPy — Complete In-Depth Guide for Python, Data Analytics & Data Science

This notebook is a **from-scratch to advanced** NumPy learning path. It keeps the reference notebook's pattern of **short theory sections followed by runnable code cells**, while expanding the coverage substantially for practical analytics, scientific computing, and data-science work.

> **Learning rule:** Run cells in order. Most examples use self-contained data so the notebook is reproducible and does not depend on external datasets.

---

## 📑 Table of Contents

1. [NumPy Overview & Setup](#1-numpy-overview--setup)
2. [Python Lists vs NumPy Arrays](#2-python-lists-vs-numpy-arrays)
3. [Creating Arrays](#3-creating-arrays)
4. [Array Dimensions: Vector, Matrix & Tensor](#4-array-dimensions-vector-matrix--tensor)
5. [Array Attributes](#5-array-attributes)
6. [Data Types (`dtype`)](#6-data-types-dtype)
7. [Indexing](#7-indexing)
8. [Slicing](#8-slicing)
9. [Reshaping, Flattening & Transposing](#9-reshaping-flattening--transposing)
10. [Copy vs View](#10-copy-vs-view)
11. [Joining, Splitting, Adding & Removing Data](#11-joining-splitting-adding--removing-data)
12. [Arithmetic & Universal Functions](#12-arithmetic--universal-functions)
13. [Aggregations and `axis`](#13-aggregations-and-axis)
14. [Broadcasting](#14-broadcasting)
15. [Comparisons, Boolean Masks & Filtering](#15-comparisons-boolean-masks--filtering)
16. [`where`, `select`, `clip`, `choose`](#16-where-select-clip-choose)
17. [Sorting, Searching & Unique Values](#17-sorting-searching--unique-values)
18. [Statistics](#18-statistics)
19. [Linear Algebra](#19-linear-algebra)
20. [Random Numbers](#20-random-numbers)
21. [Missing / Non-finite Numeric Data](#21-missing--non-finite-numeric-data)
22. [String Operations](#22-string-operations)
23. [Structured Arrays](#23-structured-arrays)
24. [Datetime and Timedelta](#24-datetime-and-timedelta)
25. [Input / Output: `.npy` and `.npz`](#25-input--output-npy-and-npz)
26. [Text I/O](#26-text-io)
27. [Performance and Memory](#27-performance-and-memory)
28. [Vectorization and Advanced Indexing](#28-vectorization-and-advanced-indexing)
29. [Business & Analytics Examples](#29-business--analytics-examples)
30. [Mini Projects](#30-mini-projects)
31. [Exercises and Interview Practice](#31-exercises-and-interview-practice)
32. [Quick Reference](#32-quick-reference)


## 1. NumPy Overview & Setup

### What is NumPy?

**NumPy (Numerical Python)** is Python's core library for numerical computing. Its central object is the **`ndarray`**, an N-dimensional homogeneous array that supports fast vectorized operations.

### Why NumPy matters in data science

- Efficient storage of numeric data.
- Vectorized operations instead of Python loops.
- Broadcasting for operations on compatible shapes.
- Statistical and mathematical functions.
- Linear algebra support.
- Random-number generation.
- Interoperability with Pandas, SciPy, scikit-learn, Matplotlib, and many other tools.

The reference material introduces NumPy through arrays, creation, dimensions, properties, reshaping, filtering, sorting, concatenation, advanced operations, business examples, and `.npy` persistence. This notebook expands that path into a complete learning sequence.


In [ ]:
from pathlib import Path
import numpy as np

print("NumPy version:", np.__version__)


In [ ]:
# A small reproducible setup used throughout the notebook
rng = np.random.default_rng(42)

print("Random generator initialized.")


### Basic mental model

Think of a NumPy array as:

`data + shape + dtype`

For example, an array with shape `(3, 4)` has 3 rows and 4 columns, while its `dtype` tells NumPy how each element is represented in memory.


In [ ]:
arr = np.array([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 100, 110, 120]])

print("Data:\n", arr)
print("Shape:", arr.shape)
print("Dtype:", arr.dtype)


## 2. Python Lists vs NumPy Arrays

Python lists are general-purpose containers. NumPy arrays are designed for numerical computation.

A key difference is **element-wise arithmetic**:

- `[1, 2, 3] * 2` repeats the list.
- `np.array([1, 2, 3]) * 2` multiplies every element by 2.


In [ ]:
py_list = [1, 2, 3]
np_array = np.array([1, 2, 3])

print("Python list * 2:", py_list * 2)
print("NumPy array * 2:", np_array * 2)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", b / a)


### Homogeneous data

A normal NumPy array normally stores one data type for all elements. Mixed input is therefore converted to a common compatible type.


In [ ]:
mixed = np.array([1, 2.5, 3,"python"])
print(mixed)
print("dtype:", mixed.dtype)


## 3. Creating Arrays

Common constructors include:

- `np.array`
- `np.zeros`
- `np.ones`
- `np.full`
- `np.empty`
- `np.arange`
- `np.linspace`
- `np.eye`
- `np.identity`
- random-generation functions

The difference between `arange` and `linspace` is important:
`arange` focuses on a **step size**, while `linspace` focuses on a **number of evenly spaced points**.


In [ ]:
from_list = np.array([1, 2, 3, 4, 5])
from_tuple = np.array((10, 20, 30))
from_range = np.array(range(5))
from_dict = np.array(list({2:34,3:36}.values()))

print(from_list)
print(from_tuple)
print(from_range)
print(from_dict)


In [ ]:
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
full = np.full((2, 2), 7)
empty = np.empty((2, 2))

print("zeros:\n", zeros)
print("\nones:\n", ones)
print("\nfull:\n", full)
print("\nempty:\n", empty)


In [ ]:
# dtype can be specified explicitly
int_array = np.zeros(5, dtype=np.int32)
float_array = np.ones(5, dtype=np.float64)

print(int_array, int_array.dtype)
print(float_array, float_array.dtype)


In [ ]:
ar = np.arange(0, 11, 2)
ls = np.linspace(0, 1, 6)

print("arange:", ar)
print("linspace:", ls)


In [ ]:
# ================================================================
# NumPy: np.eye() vs np.identity()
# ================================================================

# ----------------------------------------------------------------
# THEORY
# ----------------------------------------------------------------
# Both np.eye() and np.identity() are used to create matrices
# containing 1s on the main diagonal and 0s elsewhere.
#
# Example of a 3 x 3 identity matrix:
#
# [[1, 0, 0],
#  [0, 1, 0],
#  [0, 0, 1]]
#
# The main difference is:
#
# np.identity()
# -> Creates ONLY a square identity matrix.
# -> Syntax: np.identity(n)
# -> 'n' represents both rows and columns.
#
# np.eye()
# -> More flexible than np.identity().
# -> Can create square OR rectangular matrices.
# -> Can also shift the position of the diagonal using 'k'.
# -> Syntax: np.eye(N, M=None, k=0)
#
# Therefore:
# np.identity() = simple identity matrix
# np.eye()      = flexible diagonal matrix creator
# ----------------------------------------------------------------


# ================================================================
# 1. np.identity()
# ================================================================

# Creates a 3 x 3 identity matrix.
identity_matrix = np.identity(3)

print("np.identity(3):")
print(identity_matrix)


# ================================================================
# 2. np.eye()
# ================================================================

# Creates the same 3 x 3 identity matrix.
eye_matrix = np.eye(3)

print("\nnp.eye(3):")
print(eye_matrix)


# Both produce the same result:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


# ================================================================
# 3. IMPORTANT DIFFERENCE: Rectangular Matrix
# ================================================================

# np.eye() can create a rectangular matrix.
# Here:
#     3 = number of rows
#     4 = number of columns

rectangular_matrix = np.eye(3, 4)

print("\nnp.eye(3, 4):")
print(rectangular_matrix)

# Output:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]]


# np.identity() cannot do this because it accepts
# only one size parameter for a square matrix.


# ================================================================
# 4. np.eye() CAN SHIFT THE DIAGONAL
# ================================================================

# k=0  -> Main diagonal
# k=1  -> Diagonal above the main diagonal
# k=-1 -> Diagonal below the main diagonal

upper_diagonal = np.eye(3, k=1)

print("\nnp.eye(3, k=1):")
print(upper_diagonal)

# Output:
# [[0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]]


# ================================================================
# FINAL COMPARISON
# ================================================================

# np.identity(3)
# -> Only square identity matrix
#
# np.eye(3)
# -> Square identity matrix
#
# np.eye(3, 4)
# -> Rectangular matrix
#
# np.eye(3, k=1)
# -> Shifted diagonal
#
# So, np.eye() is more flexible, while np.identity()
# is specifically designed for creating a square identity matrix.

In [ ]:
# ================================================================
# RANDOM NUMBER GENERATION USING NUMPY'S MODERN GENERATOR API
# ================================================================

# Create a modern random number Generator
rng = np.random.default_rng()


# ------------------------------------------------
# 1. rng.random()
# ------------------------------------------------
# Generates random floating-point numbers using
# a uniform distribution.
#
# (2, 3) = shape
#       2 rows × 3 columns
#
# Values are:
#       0 <= value < 1
#
random_uniform = rng.random((2, 3))

print("1. Uniform Random Numbers:")
print(random_uniform)


# ------------------------------------------------
# 2. rng.integers()
# ------------------------------------------------
# Generates random integers.
#
# Syntax:
# rng.integers(start, stop, size=shape)
#
# 1  = starting value (included)
# 11 = stopping value (excluded)
# 
# Therefore possible values:
#       1, 2, 3, ..., 10
#
# size=(2, 3)
#       2 rows × 3 columns
#
random_integers = rng.integers(1, 11, size=(2, 3))

print("\n2. Random Integers:")
print(random_integers)


# ------------------------------------------------
# 3. rng.normal()
# ------------------------------------------------
# Generates random numbers from a normal
# (Gaussian) distribution.
#
# loc   = mean
# scale = standard deviation
# size  = number of values
#
# loc=0
#       Mean is 0
#
# scale=1
#       Standard deviation is 1
#
# size=5
#       Generate 5 values
#
random_normal = rng.normal(loc=0, scale=1, size=5)

print("\n3. Normal Distribution:")
print(random_normal)

## 4. Array Dimensions: Vector, Matrix & Tensor

- **0-D array (scalar):** one value.
- **1-D array (vector):** one axis.
- **2-D array (matrix):** rows and columns.
- **3-D+ array (tensor):** multiple axes.

`ndim` tells you how many axes the array has.


In [ ]:
scalar = np.array(42)
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

for name, x in [("scalar", scalar), ("vector", vector), ("matrix", matrix), ("tensor", tensor)]:
    print(name, "ndim =", x.ndim, "shape =", x.shape)


## 5. Array Attributes

Important attributes:

| Attribute | Meaning |
|---|---|
| `ndim` | number of axes |
| `shape` | size along each axis |
| `size` | total number of elements |
| `dtype` | element data type |
| `itemsize` | bytes per element |
| `nbytes` | total bytes consumed by the data buffer |
| `T` | transpose view |


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)
print("itemsize:", arr.itemsize)
print("nbytes:", arr.nbytes)
print("T:\n", arr.T)


## 6. Data Types (`dtype`)

NumPy supports fixed-width numeric types such as `int8`, `int16`, `int32`, `int64`, `float32`, `float64`, and Boolean types.

The dtype affects **precision, valid range, and memory usage**.


In [ ]:
values = np.array([1, 2, 3, 4], dtype=np.int32)

print(values)
print(values.dtype)


In [ ]:
float_values = values.astype(np.float64)
string_values = values.astype(str)

print("Float:", float_values, float_values.dtype)
print("String:", string_values, string_values.dtype)


In [ ]:
# A safe example of down-casting when the values fit
small = np.array([10, 20, 30], dtype=np.int64)
small32 = small.astype(np.int32)

print(small.nbytes, "bytes as int64")
print(small32.nbytes, "bytes as int32")


### Type promotion

When NumPy combines arrays of different numeric types, it usually promotes values to a type that can safely represent the result.


In [ ]:
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([0.5, 1.5, 2.5], dtype=np.float64)

result = a + b

print(result)
print("dtype:", result.dtype)


## 7. Indexing

Indexing retrieves elements from an array.

For 1-D arrays: `a[index]`

For 2-D arrays: `a[row, column]`

For higher dimensions, provide one index per axis or use slices.


In [ ]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])
print(numbers[2])
print(numbers[-1])
print(numbers[-2])


In [ ]:
matrix = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("Element [1, 2]:", matrix[1, 2])
print("Second row:", matrix[1])
print("Third column:", matrix[:, 2])


In [ ]:
numpy_array = np.arange(10)
print(numpy_array)

In [ ]:
tensor = np.arange(24).reshape(2, 3, 4)

print("tensor[0, 1, 2] =", tensor[0, 1, 2])
print("First block:\n", tensor[0])


### Negative indexing

Negative indices count from the end:

`-1` → last element  
`-2` → second-last element


In [ ]:
arr = np.array([100, 200, 300, 400, 500])

print(arr[-1], arr[-2])


## 8. Slicing

The general pattern is:

`start : stop : step`

The `stop` index is exclusive.


In [ ]:
arr = np.arange(10)

print("Your Array: ",arr)
print("arr[2:7]     =", arr[2:7])
print("arr[:5]      =", arr[:5])
print("arr[5:]      =", arr[5:])
print("arr[::2]     =", arr[::2])
print("arr[::-1]    =", arr[::-1])
print("arr[7:2:-1]  =", arr[7:2:-1])

In [ ]:
matrix = np.arange(1,17).reshape(4,4)

print(matrix)
print("Top-left 2x2:\n", matrix[:2, :2])
print("Last two rows:\n", matrix[2:, :])
print("Odd columns:\n", matrix[:, 1::2])


### Slice assignment

Unlike ordinary Python expressions, assigning to a NumPy slice changes the selected portion of the existing array.


In [ ]:
arr = np.arange(10)
print("Before:", arr)

arr[2:6] = 99
print("After :", arr)


## 9. Reshaping, Flattening & Transposing

`reshape()` changes the shape without changing the number of elements.

`flatten()` returns a copy.

`ravel()` tries to return a view when possible.

`transpose()` / `.T` reorders axes.


In [ ]:
arr = np.arange(12)

reshaped = arr.reshape(3, 4)

print("Original:", arr)
print("Reshaped:\n", reshaped)


In [ ]:
matrix = np.arange(1, 7).reshape(2, 3)

print("Original:\n", matrix)
print("\nTranspose:\n", matrix.T)
print("\nFlatten:", matrix.flatten())
print("Ravel:", matrix.ravel())


In [ ]:
# -1 lets NumPy infer one dimension
arr = np.arange(24).reshape(4, -1, 2)
print(arr.shape)


In [ ]:
# reshape does not work when the element count is incompatible
try:
    np.arange(10).reshape(3, 4)
except ValueError as e:
    print(type(e).__name__, ":", e)


### `reshape` vs `resize`

`reshape` returns a reshaped array (when possible) and leaves the original shape unchanged.
`resize` can change the array itself and can repeat or truncate data.


In [ ]:
a = np.arange(6)
b = a.reshape(2, 3)

print("a shape:", a.shape)
print("b shape:", b.shape)


In [ ]:
a = np.arange(4)

print(a)

a.resize(2, 3, refcheck=False)

print(a)
print(a.shape)

In [ ]:
a = np.arange(4)

b = np.resize(a, (2, 3))

print(b)
print(b.shape)

## 10. Copy vs View

This is one of the most important NumPy concepts.

- A **view** references the same underlying data buffer.
- A **copy** owns independent data.

Changing a view can therefore change the original array.


In [ ]:
# A view creates a new array object, but it points to the same underlying memory.
a = np.array([10, 20, 30, 40])

b = a.view()

print("a:", a)
print("b:", b)

b[0] = 100

print("After changing b:")
print("a:", a)
print("b:", b)

In [ ]:
#A copy creates a completely separate array in memory.
a = np.array([10, 20, 30, 40])

b = a.copy()

print("a:", a)
print("b:", b)

b[0] = 100

print("a:", a)
print("b:", b)

In [ ]:
arr = np.arange(6)
reshaped = arr.reshape(2, 3)

print("May share memory:", np.shares_memory(arr, reshaped))


## 11. Joining, Splitting, Adding & Removing Data

Useful functions include:

- `concatenate`
- `stack`
- `vstack`
- `hstack`
- `column_stack`
- `split`
- `array_split`
- `delete`
- `insert`
- `append`

These operations often create new arrays; they are not equivalent to efficient in-place list append semantics.


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("concatenate:", np.concatenate((a, b)))


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("vstack:\n", np.vstack((a, b)))
print("\nhstack:\n", np.hstack((a, b)))


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

print("stack axis=0:\n", np.stack((a, b), axis=0))
print("\nstack axis=1:\n", np.stack((a, b), axis=1))


In [ ]:
arr = np.arange(10)
print("split:", np.split(arr, 2))
print("array_split:", np.array_split(arr, 3))


In [ ]:
arr = np.array([10, 20, 30, 40])

print("delete:", np.delete(arr, 2))  
print("insert:", np.insert(arr, 2, 999))
print("append:", np.append(arr, [50, 60]))




### Shape compatibility

Concatenation and stacking require compatible dimensions. Always check `shape` before combining arrays.


In [ ]:
a = np.ones((2, 3))
b = np.zeros((4, 3))

print("Compatible for vstack:", a.shape[1:] == b.shape[1:])
print("a:", a.shape, "b:", b.shape)


## 12. Arithmetic & Universal Functions

NumPy's **ufuncs** perform element-wise operations efficiently.

Common functions include:

`add`, `subtract`, `multiply`, `divide`, `power`, `sqrt`, `abs`, `exp`, `log`, `sin`, `cos`, and many more.


In [ ]:
a = np.array([1, 4, 9, 16])

print("sqrt:", np.sqrt(a))
print("square:", np.square(a))
print("absolute:", np.abs(np.array([-3, 2, -8])))


In [ ]:
x = np.array([1.0, 2.0, 3.0])

print("exp:", np.exp(x))
print("log:", np.log(x))
print("log10:", np.log10(x))


In [ ]:
angles = np.array([0, np.pi / 2, np.pi])

print("sin:", np.sin(angles))
print("cos:", np.cos(angles))


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(np.add(a, b))
print(np.multiply(a, b))
print(np.power(a, 2))


### Operator precedence

Remember that `**` has higher precedence than multiplication, and parentheses make intent explicit.


In [ ]:
x = np.array([1, 2, 3])

print("x * 2 + 1:", x * 2 + 1)
print("(x * 2) + 1:", (x * 2) + 1)


## 13. Aggregations and `axis`

Aggregation functions reduce arrays:

- `sum`
- `min`
- `max`
- `mean`
- `median`
- `std`
- `var`
- `prod`

### Understanding `axis`

For a 2-D array:

- `axis=0` reduces **down rows** and produces one result per column.
- `axis=1` reduces **across columns** and produces one result per row.

A reliable rule: the specified axis is the dimension that disappears.


In [ ]:
sales = np.array([[100, 120, 130],
                     [200, 180, 220],
                     [150, 170, 160]])

print("Total:", sales.sum())
print("Column totals (axis=0):", sales.sum(axis=0))
print("Row totals (axis=1):", sales.sum(axis=1))


In [ ]:
print("Column minimum:", sales.min(axis=0))
print("Row maximum:", sales.max(axis=1))
print("Column means:", sales.mean(axis=0))
print("Row means:", sales.mean(axis=1))


In [ ]:
print("Median:", np.median(sales))
print("Std:", np.std(sales))
print("Variance:", np.var(sales))


In [ ]:
# keepdims preserves reduced dimensions
row_totals = sales.sum(axis=1, keepdims=True)

print(row_totals)
print("Shape:", row_totals.shape)


In [ ]:
# argmax / argmin return positions
scores = np.array([91, 72, 99, 88])

print("Best position:", np.argmax(scores))
print("Best score:", np.max(scores))
print("Worst position:", np.argmin(scores))


## 14. Broadcasting

Broadcasting lets NumPy operate on arrays with different but compatible shapes.

A simplified compatibility rule compares dimensions from the right:

Two dimensions are compatible when they are equal, or one of them is `1`.

This avoids writing explicit loops in many data-science calculations.


In [ ]:
a = np.array([1, 2, 3])
print(a + 10)


In [ ]:
matrix = np.array([[1, 2, 3],
                      [4, 5, 6]])
print(matrix.shape)

offset = np.array([10, 20, 30])
print(offset.shape)

print(matrix + offset)


In [ ]:
column = np.array([[10], [20], [30]])
row = np.array([1, 2, 3])

print("Column shape:", column.shape)
print("Row shape:", row.shape)
print("\nBroadcast result:\n", column + row)


In [ ]:
# Broadcasting failure example
a = np.ones((2, 3))
b = np.ones((4,))

try:
    print(a + b)
except ValueError as e:
    print(type(e).__name__, ":", e)


### Business use: adjusting values by a common factor

Broadcasting is useful when every column or every observation must receive a different adjustment.


In [ ]:
revenue = np.array([[1000, 1200, 900],
                       [1500, 1600, 1700]])

discount_rate = np.array([0.10, 0.05, 0.20])

net_revenue = revenue * (1 - discount_rate)

print(net_revenue)


## 15. Comparisons, Boolean Masks & Filtering

NumPy comparisons return Boolean arrays. These can be used as masks for filtering.

This is one of the most important patterns in analytics:

```python
mask = values > threshold
filtered = values[mask]
```


In [ ]:
numbers = np.arange(1, 11)

mask = numbers % 2 == 0

print("Mask:", mask)
print("Even values:", numbers[mask])


In [ ]:
# In Python We use filter Function to perform filteration 
numbers = list(range(1, 11))

even_values = list(filter(lambda x: x % 2 == 0, numbers))

print(even_values)

In [ ]:
numbers = np.arange(1, 11)

print("Greater than 5:", numbers[numbers > 5])
print("Between 3 and 8:", numbers[(numbers >= 3) & (numbers <= 8)])


In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)

print("Values > 5:")
print(matrix>5)
print(matrix[matrix > 5])

In [ ]:
# Any / all are useful for validation
arr = np.array([10, 20, 30])

print("All > 0:", np.all(arr > 0))
print("Any > 25:", np.any(arr > 25))


In [ ]:
# Combining conditions requires &, |, and ~ with parentheses
arr = np.arange(1, 11)

mask = ((arr % 2 == 0) | (arr == 5)) & (arr < 9)

print(arr[mask])


## 16. `where`, `select`, `clip`, `choose`

### `np.where`

`np.where(condition, x, y)` chooses values element-wise.

It can also be called with only a condition to obtain indices where a condition is true.


In [ ]:
scores = np.array([45, 68, 82, 91, 37])

grades = np.where(scores >= 50, "Pass", "Fail")

print(grades)


In [ ]:
scores = np.array([45, 68, 82, 91, 37])

passing_indices = np.where(scores >= 50)

print("Indices:", passing_indices)
print("Passing scores:", scores[passing_indices])


In [ ]:
temperature = np.array([-5, 10, 22, 40])

safe = np.clip(temperature, 0, 30)

print("Original:", temperature)
print("Clipped:", safe)


In [ ]:
x = np.arange(1, 7)

result = np.select(
    [x < 3, x < 5, x >= 5],
    ["Low", "Medium", "High"],
    default="Unknown"
)

print(result)


### Fancy indexing

Fancy indexing uses an array/list of indices to select arbitrary positions.


In [ ]:
numbers = np.array([10, 20, 30, 40, 50])

indices = [0, 2, 4]

print(numbers[indices])


In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)

rows = [0, 2]
cols = [1, 2]

print("Paired advanced indexing:", matrix[rows, cols])


## 17. Sorting, Searching & Unique Values

Important tools:

- `np.sort`
- `np.argsort`
- `np.partition`
- `np.searchsorted`
- `np.unique`
- `np.nonzero`
- `np.flatnonzero`

A critical distinction:

- `sort` gives sorted **values**.
- `argsort` gives the **indices that would sort** the values.


In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2])

print("Sorted:", np.sort(unsorted))
print("Original:", unsorted)


In [ ]:
unsorted = np.array([30, 10, 50, 20])

order = np.argsort(unsorted)
print("Order:", order)
print("Sorted:", unsorted[order])


In [ ]:
matrix = np.array([[3, 1, 2],
                     [6, 5, 4]])

print("Sort each row:\n", np.sort(matrix, axis=1))
print("Sort each column:\n", np.sort(matrix, axis=0))


In [ ]:
values = np.array([1, 2, 2, 3, 3, 3, 4,3,4])

unique_values, counts = np.unique(values, return_counts=True)

print("Unique:", unique_values)
print("Counts:", counts)


In [ ]:
matrix = np.array([
    [1, 2],
    [3, 4],
    [1, 2],
    [5, 6]
])

unique_rows = np.unique(matrix, axis=0)

print(unique_rows)

unique_columns = np.unique(matrix, axis=1)

print(unique_columns)

In [ ]:
sorted_values = np.array([10, 20, 30, 40, 50])

print("Insert position for 25:", np.searchsorted(sorted_values, 25))
print("Positions for [15, 35]:", np.searchsorted(sorted_values, [15, 35]))


In [ ]:
arr = np.array([0, 5, 0, 7, 0, 9])

print("nonzero:", np.nonzero(arr))
print("flatnonzero:", np.flatnonzero(arr))


## 18. Statistics

NumPy provides descriptive statistics that are frequently used before moving into Pandas or machine learning.

Common measures:

- mean
- median
- percentile
- quantile
- variance
- standard deviation
- min / max
- covariance
- correlation


In [ ]:
data = np.array([10, 12, 15, 18, 25, 30, 35])

print("Mean:", np.mean(data))
print("Median:", np.median(data))

""" 
Class A: 48, 49, 50, 51, 52
Class B: 10, 30, 50, 70, 90
""" 

print("Std:", np.std(data))
print("Variance:", np.var(data))


In [ ]:
data = np.array([10, 12, 15, 18, 25, 30, 35])

print("25th percentile:", np.percentile(data, 25))
print("75th percentile:", np.percentile(data, 75))
print("25% quantile:", np.quantile(data, 0.25))


In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 8, 10])

print("Covariance matrix:\n", np.cov(x, y))
print("Correlation matrix:\n", np.corrcoef(x, y))


### Weighted average

A weighted average gives some observations more influence than others.


In [152]:
scores = np.array([70, 80, 90])
weights = np.array([1, 2, 3])

print(np.average(scores, weights=weights))


83.33333333333333


## 19. Linear Algebra

NumPy includes matrix-oriented operations such as:

- matrix multiplication (`@`, `np.matmul`)
- dot products
- transpose
- determinant
- inverse
- solving linear systems
- eigenvalues/eigenvectors
- norms

Use `@` for matrix multiplication; `*` is element-wise multiplication.


In [153]:
A = np.array([[1, 2],
                [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Element-wise *:\n", A * B)
print("\nMatrix @ multiplication:\n", A @ B)


Element-wise *:
 [[ 5 12]
 [21 32]]

Matrix @ multiplication:
 [[19 22]
 [43 50]]


In [154]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Dot product:", np.dot(x, y))
print("Vector @ vector:", x @ y)


Dot product: 32
Vector @ vector: 32


In [155]:
A = np.array([[4, 7],
                [2, 6]])

print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))


Determinant: 10.000000000000002
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


# Solving Linear Equation
A = [[3, 1],
     [1, 2]]

b = [9, 8]

        ↓

       Ax = b

        ↓

[3  1] [x]   [9]
[1  2] [y] = [8]

        ↓

3x + y = 9
x + 2y = 8

        ↓

x = 2
y = 3

        ↓

solution = [2, 3]

        ↓

A @ solution

        ↓

[9, 8]

        ↓

Same as b ✅

In [156]:
A = np.array([[3, 1],
                [1, 2]])
b = np.array([9, 8])

solution = np.linalg.solve(A, b)

print("Solution:", solution)
print("Check:", A @ solution)


Solution: [2. 3.]
Check: [9. 8.]


In [ ]:
A = np.array([[1, -1],
                [1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


In [ ]:
v = np.array([3, 4])

print("Euclidean norm:", np.linalg.norm(v))


## 20. Random Numbers

Use `np.random.default_rng()` rather than relying on the older global random-state API.

Important ideas:

- reproducibility with a seed
- integer generation
- uniform distributions
- normal distributions
- random choice
- shuffling
- permutation


In [ ]:
generator = np.random.default_rng(123)

print(generator.integers(1, 7, size=10))


In [157]:
generator = np.random.default_rng(123)

print("Uniform:", generator.uniform(0, 1, 5))
print("Normal:", generator.normal(100, 15, 5))


Uniform: [0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
Normal: [108.65655687  90.4530453  108.12928331  95.25106823  95.16416326]


In [158]:
generator = np.random.default_rng(123)

choices = np.array(["A", "B", "C"])

print("Choice:", generator.choice(choices, size=10))


Choice: ['A' 'C' 'B' 'A' 'C' 'A' 'A' 'A' 'B' 'A']


In [ ]:
generator = np.random.default_rng(123)

arr = np.arange(1, 11)

shuffled = arr.copy()
generator.shuffle(shuffled)

print("Original:", arr)
print("Shuffled:", shuffled)
print("Permutation:", generator.permutation(arr))


### Reproducibility

The same seed produces the same pseudo-random sequence, which is essential for debugging and experiments.


In [ ]:
r1 = np.random.default_rng(42).random(5)
r2 = np.random.default_rng(42).random(5)

print("Same sequence:", np.array_equal(r1, r2))
print(r1)


## 21. Missing / Non-finite Numeric Data

NumPy commonly represents missing numeric values with `np.nan`.

Related special values:

- `np.nan` — not-a-number
- `np.inf` — positive infinity
- `-np.inf` — negative infinity

Use `np.isnan`, `np.isfinite`, `np.isinf`, and `nan*` functions where appropriate.


In [159]:
values = np.array([10.0, np.nan, 20.0, np.inf, -np.inf])

print("isnan:", np.isnan(values))
print("isfinite:", np.isfinite(values))
print("isinf:", np.isinf(values))


isnan: [False  True False False False]
isfinite: [ True False  True False False]
isinf: [False False False  True  True]


In [ ]:
values = np.array([10.0, np.nan, 20.0, np.nan])

print("np.mean:", np.mean(values))
print("np.nanmean:", np.nanmean(values))
print("np.nansum:", np.nansum(values))


In [ ]:
values = np.array([10.0, np.nan, 20.0, np.nan])

filled = np.where(np.isnan(values), np.nanmean(values), values)

print("Original:", values)
print("Filled with mean:", filled)


## 22. String Operations

NumPy has `np.char` functionality and, in newer NumPy versions, string-related functionality can be handled through dedicated string dtypes/APIs.

For general data analytics, Pandas is usually more convenient for large text columns, but NumPy string arrays are useful for learning array-based string operations.


In [160]:
names = np.array(["raj", "amit", "neha"])

print(np.char.upper(names))
print(np.char.title(names))


['RAJ' 'AMIT' 'NEHA']
['Raj' 'Amit' 'Neha']


In [161]:
names = np.array(["Ravi Kumar", "Amit Shah", "Neha Singh"])

print(np.char.find(names, "a"))
print(np.char.replace(names, " ", "_"))


[1 7 3]
['Ravi_Kumar' 'Amit_Shah' 'Neha_Singh']


In [162]:
values = np.array(["apple", "banana", "apple", "orange"])

print(np.unique(values))


['apple' 'banana' 'orange']


## 23. Structured Arrays

Structured arrays let one NumPy array contain fields with different dtypes.

They are useful when you want a low-level, NumPy-native record layout. For day-to-day analytics, however, Pandas DataFrames are usually easier to work with.


In [ ]:
dtype = np.dtype([
    ("id", "i4"),
    ("name", "U20"),
    ("salary", "f8")
])

employees = np.array([
    (1, "Ravi", 50000),
    (2, "Amit", 60000),
    (3, "Neha", 55000)
], dtype=dtype)

print(employees)


In [ ]:
print("IDs:", employees["id"])
print("Names:", employees["name"])
print("Salary:", employees["salary"])


In [ ]:
high_paid = employees[employees["salary"] > 55000]

print(high_paid)


## 24. Datetime and Timedelta

NumPy supports date/time values through `datetime64` and `timedelta64`.

These are useful for arithmetic on dates and durations.


In [ ]:
dates = np.array(["2026-01-01", "2026-01-10", "2026-02-01"], dtype="datetime64[D]")

print(dates)
print("dtype:", dates.dtype)


In [ ]:
dates = np.array(["2026-01-01", "2026-01-10"], dtype="datetime64[D]")

print("Difference:", dates[1] - dates[0])
print("One week later:", dates + np.timedelta64(7, "D"))


In [ ]:
start = np.datetime64("2026-01-01")
end = np.datetime64("2026-03-15")

days = (end - start) / np.timedelta64(1, "D")

print("Days between:", days)


## 25. Input / Output: `.npy` and `.npz`

NumPy provides binary persistence formats:

- `.npy` stores one NumPy array.
- `.npz` stores multiple arrays.

These preserve NumPy-specific dtype and shape information and are convenient for NumPy-to-NumPy workflows.


In [ ]:

# 1. Create path for folder
io_dir = Path(".numpy_io_demo")

# 2. Create folder
io_dir.mkdir(exist_ok=True)

# 3. Create array
array1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 4. Create file path
npy_path = io_dir / "array1.npy"

# 5. Save array
np.save(npy_path, array1)

print("Saved:", npy_path)

# 6. Load it again
loaded_array = np.load(npy_path)

print("Loaded:")
print(loaded_array)

In [ ]:
loaded_array1 = np.load(".numpy_io_demo/array1.npy")

print(loaded_array1)
print("Equal to original:", np.array_equal(loaded_array1, array1))


In [ ]:
array2 = np.arange(5)
array3 = np.eye(3)

np.savez(".numpy_io_demo/multiple_arrays.npz", first=array2, identity=array3)

loaded = np.load(".numpy_io_demo/multiple_arrays.npz")

print("Keys:", loaded.files)
print("first:", loaded["first"])
print("identity:\n", loaded["identity"])

loaded.close()


### Compressed `.npz`

`savez_compressed` trades some CPU time for smaller files.


In [ ]:
np.savez_compressed(
    ".numpy_io_demo/compressed_arrays.npz",
    values=np.arange(1000),
    matrix=np.eye(20)
)

print("Compressed file created.")


## 26. Text I/O

NumPy provides `savetxt` and `loadtxt` for simple rectangular numeric text files.

These are most appropriate when the data is numeric and regularly structured. CSV files containing mixed types, quoted text, missing-value conventions, and metadata are usually better handled by Python's `csv` module or Pandas.


In [ ]:
matrix = np.array([[1.5, 2.5, 3.5],
                      [4.5, 5.5, 6.5]])

np.savetxt(".numpy_io_demo/matrix.txt", matrix, delimiter=",", fmt="%.2f")

print("Saved text matrix.")


In [ ]:
loaded_matrix = np.loadtxt(".numpy_io_demo/matrix.txt", delimiter=",")

print(loaded_matrix)


In [ ]:
# Header and footer control
np.savetxt(
    ".numpy_io_demo/with_header.txt",
    matrix,
    delimiter=",",
    header="A,B,C",
    comments=""
)

print(Path(".numpy_io_demo/with_header.txt").read_text())


## 27. Performance and Memory

NumPy's speed comes from compact typed arrays and compiled/vectorized operations.

Key habits:

- Prefer vectorized operations.
- Avoid Python loops over individual numeric elements when a NumPy operation exists.
- Choose appropriate dtypes.
- Reuse arrays when practical.
- Avoid unnecessary copies.
- Be aware of temporary arrays created by expressions.


In [ ]:
import time

n = 1_000_000
data = np.arange(n, dtype=np.float64)

start = time.perf_counter()
result_vectorized = data * 2 + 5
vectorized_time = time.perf_counter() - start

print("Vectorized time:", vectorized_time)
print("First 5:", result_vectorized[:5])


In [ ]:
# A Python-loop comparison (kept at a smaller scale so it stays practical)
small_data = list(range(200_000))

start = time.perf_counter()
loop_result = [x * 2 + 5 for x in small_data]
loop_time = time.perf_counter() - start

print("List-comprehension time:", loop_time)
print("First 5:", loop_result[:5])


In [ ]:
dtype_sizes = {
    "int8": np.dtype(np.int8).itemsize,
    "int32": np.dtype(np.int32).itemsize,
    "int64": np.dtype(np.int64).itemsize,
    "float32": np.dtype(np.float32).itemsize,
    "float64": np.dtype(np.float64).itemsize,
}

print(dtype_sizes)


In [ ]:
a32 = np.zeros(1_000_000, dtype=np.float32)
a64 = np.zeros(1_000_000, dtype=np.float64)

print("float32 bytes:", a32.nbytes)
print("float64 bytes:", a64.nbytes)


### Controlling copies

Operations such as `astype`, `copy`, concatenation, and some advanced indexing patterns create new arrays. Use `np.shares_memory` when you need to understand whether two arrays share storage.


In [ ]:
base = np.arange(10)
slice_view = base[2:7]
advanced = base[[2, 3, 4]]

print("slice shares memory:", np.shares_memory(base, slice_view))
print("advanced indexing shares memory:", np.shares_memory(base, advanced))


## 28. Vectorization and Advanced Indexing

Advanced indexing becomes powerful when selecting or updating arbitrary rows and columns.

Use it carefully: advanced indexing typically returns a copy rather than a view.


In [ ]:
data = np.arange(20).reshape(5, 4)

selected_rows = data[[0, 2, 4]]
selected_columns = data[:, [0, 2]]

print("Selected rows:\n", selected_rows)
print("\nSelected columns:\n", selected_columns)


In [ ]:
data = np.arange(20).reshape(5, 4)

data[[0, 2], [1, 3]] = 999

print(data)


### `np.vectorize`

`np.vectorize` can make a Python function *look* vectorized, but it is primarily a convenience wrapper rather than a replacement for truly vectorized NumPy ufuncs.

Use native NumPy operations when available.


In [ ]:
def classify(x):
    if x >= 50:
        return "Pass"
    return "Fail"

scores = np.array([40, 55, 80, 35])

vectorized_classify = np.vectorize(classify)

print(vectorized_classify(scores))


## 29. Business & Analytics Examples

The reference material uses a restaurant sales example with rows representing restaurants and columns representing yearly sales. The examples below preserve that analytics-oriented style and extend it with more realistic analysis patterns.


In [163]:
# Structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 190000],
    [3, 200000, 210000, 230000, 260000],
    [4,  90000, 110000, 125000, 145000],
    [5, 175000, 190000, 205000, 240000],
])

print(sales_data)


[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 210000 230000 260000]
 [     4  90000 110000 125000 145000]
 [     5 175000 190000 205000 240000]]


In [172]:
Total_sum = (np.sum(sales_data[:,2:3], axis = 1))
print(np.sum(Total_sum))


830000


In [169]:
yearly_totals = np.sum(sales_data[:, 1:], axis=1)
print("Total sales by year:", yearly_totals)


Total sales by year: [800000 610000 900000 470000 810000]


In [173]:
restaurant_totals = np.sum(sales_data[:, 1:], axis=0)

print("Total sales per restaurant:")
print(restaurant_totals)


Total sales per restaurant:
[ 735000  830000  940000 1085000]


In [123]:
average_yearly_sales = np.mean(sales_data[:, 1:], axis=0)
print("Average per restaurant by year:", average_yearly_sales)


In [174]:
best_restaurant_index = np.argmax(restaurant_totals)

print("Best restaurant row index:", best_restaurant_index)
print("Restaurant ID:", sales_data[best_restaurant_index, 0])
print("Total:", restaurant_totals[best_restaurant_index])


Best restaurant row index: 3
Restaurant ID: 4
Total: 1085000


In [125]:
cumulative_sales = np.cumsum(sales_data[:, 1:], axis=1)

print("Cumulative sales by restaurant:\n", cumulative_sales)


Cumulative sales by restaurant:
 [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 410000 640000 900000]
 [ 90000 200000 325000 470000]
 [175000 365000 570000 810000]]


In [126]:
growth_2021_to_2024 = (
    (sales_data[:, 4] - sales_data[:, 1]) / sales_data[:, 1]
) * 100

print("Growth percentage:", growth_2021_to_2024)


Growth percentage: [66.66666667 58.33333333 30.         61.11111111 37.14285714]


In [127]:
monthly_average = sales_data[:, 1:] / 12

print("Average monthly sales for each restaurant/year:\n", monthly_average)


Average monthly sales for each restaurant/year:
 [[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 17500.         19166.66666667 21666.66666667]
 [ 7500.          9166.66666667 10416.66666667 12083.33333333]
 [14583.33333333 15833.33333333 17083.33333333 20000.        ]]


In [128]:
# Rank restaurants by total sales
ranking = np.argsort(restaurant_totals)[::-1]

print("Restaurant IDs ranked:", sales_data[ranking, 0])
print("Totals ranked:", restaurant_totals[ranking])


Restaurant IDs ranked: [3 5 1 2 4]
Totals ranked: [900000 810000 800000 610000 470000]


### Customer/order example

NumPy is useful for fast numerical calculations such as revenue, discounting, quantities, and margins.


In [129]:
quantity = np.array([10, 5, 8, 12])
price = np.array([100, 250, 80, 50])
discount = np.array([0.10, 0.05, 0.00, 0.15])

gross = quantity * price
discount_amount = gross * discount
net = gross - discount_amount

print("Gross:", gross)
print("Discount:", discount_amount)
print("Net:", net)
print("Total net revenue:", net.sum())


Gross: [1000 1250  640  600]
Discount: [100.   62.5   0.   90. ]
Net: [ 900.  1187.5  640.   510. ]
Total net revenue: 3237.5


### Inventory reorder example

Broadcasting and Boolean masks can be combined for inventory rules.


In [130]:
stock = np.array([12, 45, 5, 80, 7])
reorder_level = np.array([20, 30, 10, 50, 10])

needs_reorder = stock < reorder_level

print("Needs reorder:", needs_reorder)
print("Items needing reorder:", np.flatnonzero(needs_reorder))


Needs reorder: [ True False  True False  True]
Items needing reorder: [0 2 4]


### KPI normalization

A common analytical task is converting raw values into ratios or percentages.


In [131]:
sales = np.array([100, 150, 200, 250])

share = sales / sales.sum() * 100

print("Sales share (%):", share)
print("Sum:", share.sum())


Sales share (%): [14.28571429 21.42857143 28.57142857 35.71428571]
Sum: 100.0


## 30. Mini Projects

The projects below are designed as progressively harder practice. Every project is runnable in the notebook and uses generated data rather than requiring a downloaded dataset.


### Project 1 — Sales Summary

Goal: calculate totals, averages, best-performing periods, and rankings from a sales matrix.


In [132]:
project_sales = np.array([
    [1200, 1500, 1700, 1800],
    [ 900, 1100, 1300, 1250],
    [2000, 2100, 2300, 2600],
    [1500, 1400, 1600, 1900],
])

totals_by_month = project_sales.sum(axis=0)
totals_by_store = project_sales.sum(axis=1)
store_rank = np.argsort(totals_by_store)[::-1]

print("Monthly totals:", totals_by_month)
print("Store totals:", totals_by_store)
print("Store ranking:", store_rank)


Monthly totals: [5600 6100 6900 7550]
Store totals: [6200 4550 9000 6400]
Store ranking: [2 3 0 1]


### Project 2 — Customer Segmentation with Rules

Create simple customer segments from age and annual spend.


In [133]:
ages = np.array([21, 35, 28, 52, 41, 67, 24, 30])
spend = np.array([200, 1500, 700, 3200, 2400, 800, 450, 1700])

high_value = spend >= 2000
young = ages < 30
mid_value = (spend >= 500) & (spend < 2000)

print("High-value customers:", np.flatnonzero(high_value))
print("Young customers:", np.flatnonzero(young))
print("Mid-value customers:", np.flatnonzero(mid_value))


High-value customers: [3 4]
Young customers: [0 2 6]
Mid-value customers: [1 2 5 7]


### Project 3 — Z-score Standardization

Standardization is common before many machine-learning algorithms.

Formula:

`z = (x - mean) / std`


In [134]:
values = np.array([10, 12, 15, 18, 20, 25, 30], dtype=float)

z_scores = (values - values.mean()) / values.std()

print("Z-scores:", z_scores)
print("Mean:", z_scores.mean())
print("Std:", z_scores.std())


Z-scores: [-1.3012766  -0.99764539 -0.54219858 -0.08675177  0.21687943  0.97595745
  1.73503547]
Mean: -1.5860328923216522e-16
Std: 1.0


### Project 4 — Outlier Detection

Use the IQR rule:

- Q1 = 25th percentile
- Q3 = 75th percentile
- IQR = Q3 − Q1
- Lower bound = Q1 − 1.5 × IQR
- Upper bound = Q3 + 1.5 × IQR


In [135]:
data = np.array([10, 12, 11, 13, 12, 14, 15, 13, 12, 100], dtype=float)

q1, q3 = np.percentile(data, [25, 75])
iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers = data[(data < lower) | (data > upper)]

print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Bounds:", lower, upper)
print("Outliers:", outliers)


Q1: 12.0
Q3: 13.75
IQR: 1.75
Bounds: 9.375 16.375
Outliers: [100.]


### Project 5 — Monte Carlo Estimate of π

Generate random points in a unit square and estimate π from the fraction that lands inside a quarter circle.


In [136]:
generator = np.random.default_rng(42)

n = 200_000
points = generator.random((n, 2))

inside = (points[:, 0] ** 2 + points[:, 1] ** 2) <= 1
pi_estimate = 4 * inside.mean()

print("Estimated pi:", pi_estimate)
print("NumPy pi:", np.pi)


Estimated pi: 3.1494
NumPy pi: 3.141592653589793


### Project 6 — Matrix-Based Linear Model Calculation

For a small linear system `Ax = b`, use `np.linalg.solve` rather than explicitly calculating an inverse when solving the system.


In [137]:
A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 4]
], dtype=float)

b = np.array([10, 18, 14], dtype=float)

x = np.linalg.solve(A, b)

print("Solution:", x)
print("Residual:", A @ x - b)


Solution: [1.78947368 3.36842105 3.05263158]
Residual: [0. 0. 0.]


### Project 7 — Multi-file NumPy Artifact Workflow

Save several arrays in one `.npz` artifact, reload them, and verify their shapes and values.


In [138]:
artifact_path = Path(".numpy_io_demo") / "analytics_artifact.npz"

features = np.array([[1.2, 3.4], [2.3, 4.5], [3.1, 5.0]])
target = np.array([10.0, 15.0, 19.0])

np.savez(artifact_path, features=features, target=target)

with np.load(artifact_path) as artifact:
    print("Keys:", artifact.files)
    print("Features shape:", artifact["features"].shape)
    print("Target shape:", artifact["target"].shape)


Keys: ['features', 'target']
Features shape: (3, 2)
Target shape: (3,)


## 31. Exercises and Interview Practice

These are intentionally mixed rather than grouped only by topic.


### Exercise 1 — Create a 4×5 array containing 1–20 and calculate row and column sums.

In [139]:
exercise1 = np.arange(1, 21).reshape(4, 5)

print(exercise1)
print("Row sums:", exercise1.sum(axis=1))
print("Column sums:", exercise1.sum(axis=0))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row sums: [15 40 65 90]
Column sums: [34 38 42 46 50]


### Exercise 2 — Extract all even numbers greater than 10 from 1–30.

In [140]:
exercise2 = np.arange(1, 31)
result = exercise2[(exercise2 > 10) & (exercise2 % 2 == 0)]
print(result)


[12 14 16 18 20 22 24 26 28 30]


### Exercise 3 — Replace all negative values with zero.

In [141]:
exercise3 = np.array([-5, 3, -2, 8, -1, 10])
exercise3 = np.where(exercise3 < 0, 0, exercise3)
print(exercise3)


[ 0  3  0  8  0 10]


### Exercise 4 — Find the indices of the three largest values.

In [142]:
exercise4 = np.array([10, 90, 30, 70, 50, 100, 20])
order = np.argsort(exercise4)
top3 = order[-3:][::-1]

print("Indices:", top3)
print("Values:", exercise4[top3])


Indices: [5 1 3]
Values: [100  90  70]


### Exercise 5 — Compute a row-wise percentage contribution matrix.

In [143]:
exercise5 = np.array([
    [20, 30, 50],
    [10, 40, 50],
    [25, 25, 50]
], dtype=float)

percent = exercise5 / exercise5.sum(axis=1, keepdims=True) * 100

print(percent)


[[20. 30. 50.]
 [10. 40. 50.]
 [25. 25. 50.]]


### Exercise 6 — Normalize an array to the range 0–1.

In [144]:
exercise6 = np.array([20, 30, 50, 80], dtype=float)
normalized = (exercise6 - exercise6.min()) / (exercise6.max() - exercise6.min())

print(normalized)


[0.         0.16666667 0.5        1.        ]


### Exercise 7 — Check whether two arrays are equal.

In [145]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

print("Exact equality:", np.array_equal(a, b))


Exact equality: True


### Exercise 8 — Compare floating-point arrays safely.

In [146]:
a = np.array([0.1 + 0.2])
b = np.array([0.3])

print("Exact:", np.array_equal(a, b))
print("Close:", np.allclose(a, b))


Exact: False
Close: True


### Exercise 9 — Replace NaN values with the column mean in a 2-D numeric array.

In [147]:
exercise9 = np.array([
    [10.0, np.nan, 30.0],
    [20.0, 40.0, np.nan],
    [30.0, 50.0, 60.0]
])

for col in range(exercise9.shape[1]):
    column = exercise9[:, col]
    mean = np.nanmean(column)
    mask = np.isnan(column)
    column[mask] = mean

print(exercise9)


[[10. 45. 30.]
 [20. 40. 45.]
 [30. 50. 60.]]


### Exercise 10 — Calculate a moving average using a simple convolution.

In [148]:
values = np.array([10, 20, 30, 40, 50], dtype=float)
window = np.ones(3) / 3

moving_average = np.convolve(values, window, mode="valid")

print(moving_average)


[20. 30. 40.]


### Exercise 11 — Explain the difference between `*` and `@`.

`*` performs element-wise multiplication.

`@` performs matrix multiplication for compatible arrays.


In [149]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A * B:\n", A * B)
print("\nA @ B:\n", A @ B)


A * B:
 [[ 5 12]
 [21 32]]

A @ B:
 [[19 22]
 [43 50]]


### Exercise 12 — Explain what `axis=0` means for a 2-D array.

It reduces the first axis (rows), leaving one value per column.


In [150]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("axis=0:", x.sum(axis=0))
print("axis=1:", x.sum(axis=1))


axis=0: [5 7 9]
axis=1: [ 6 15]


## 32. Quick Reference

### Array creation

```python
np.array(...)
np.zeros(...)
np.ones(...)
np.full(...)
np.arange(...)
np.linspace(...)
np.eye(...)
np.random.default_rng(...)
```

### Shape / inspection

```python
a.ndim
a.shape
a.size
a.dtype
a.itemsize
a.nbytes
```

### Selection

```python
a[i]
a[i, j]
a[start:stop:step]
a[mask]
a[[indices]]
```

### Reshaping

```python
a.reshape(...)
a.ravel()
a.flatten()
a.T
np.transpose(a)
```

### Aggregation

```python
np.sum(a, axis=...)
np.mean(a, axis=...)
np.median(a)
np.std(a)
np.var(a)
np.min(a)
np.max(a)
np.argmin(a)
np.argmax(a)
```

### Filtering

```python
mask = a > value
a[mask]
np.where(...)
np.select(...)
np.clip(...)
```

### Sorting / uniqueness

```python
np.sort(a)
np.argsort(a)
np.unique(a)
np.searchsorted(...)
```

### Combining

```python
np.concatenate(...)
np.stack(...)
np.vstack(...)
np.hstack(...)
np.split(...)
np.array_split(...)
```

### Linear algebra

```python
A @ B
np.dot(...)
np.linalg.solve(...)
np.linalg.det(...)
np.linalg.inv(...)
np.linalg.eig(...)
np.linalg.norm(...)
```

### Persistence

```python
np.save(...)
np.load(...)
np.savez(...)
np.savez_compressed(...)
np.savetxt(...)
np.loadtxt(...)
```

### Production-minded habits

1. Check `shape` and `dtype` early.
2. Prefer vectorized NumPy operations over Python loops.
3. Use Boolean masks for filtering.
4. Understand broadcasting before combining arrays.
5. Distinguish views from copies.
6. Use `np.random.default_rng(seed)` for reproducible experiments.
7. Use `np.allclose` for floating-point comparisons.
8. Choose dtypes deliberately when memory matters.
9. Use `np.load` with care when loading data from untrusted sources.
10. Move to Pandas when your task is primarily tabular, labeled-data manipulation rather than pure numerical array computation.

---

## 🎯 Recommended Study Sequence

**Foundation → Arrays → Indexing → Reshaping → Operations → Axis → Broadcasting → Filtering → Sorting → Statistics → Linear Algebra → Random → I/O → Performance → Analytics Projects**

The most important conceptual milestones are:

**`ndarray` → `shape` → `dtype` → `axis` → broadcasting → vectorization → views/copies → advanced indexing**

Once these are solid, NumPy becomes much easier to use inside Pandas, Matplotlib, machine learning, and scientific-computing workflows.


## ✅ Notebook Completion Check

Run this final cell to verify that the core NumPy environment and examples are available.


In [151]:
checks = {
    "NumPy imported": "np" in globals(),
    "NumPy array works": isinstance(np.array([1, 2, 3]), np.ndarray),
    "Random generator works": isinstance(np.random.default_rng(1).random(1), np.ndarray),
    "I/O demo directory exists": Path(".numpy_io_demo").exists(),
}

for name, passed in checks.items():
    print(("✅" if passed else "❌"), name)

print("\nNumPy notebook core checks complete.")


✅ NumPy imported
✅ NumPy array works
✅ Random generator works
✅ I/O demo directory exists

NumPy notebook core checks complete.
